<a href="https://colab.research.google.com/github/rabiyulfahimhasim786/opencv-basics/blob/main/pdf_to_tabes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
!pip install camelot-py[cv] tabula-py

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: camelot-py[cv] in /usr/local/lib/python3.7/dist-packages (0.10.1)
Requirement already satisfied: tabula-py in /usr/local/lib/python3.7/dist-packages (2.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from tabula-py) (1.21.6)
Requirement already satisfied: distro in /usr/local/lib/python3.7/dist-packages (from tabula-py) (1.7.0)
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.7/dist-packages (from tabula-py) (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.3->tabula-py) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.3->tabula-py) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.25.3->tabula-py) (1.15.0)
Requirement already satisfied: openpyxl>=2.5.8 in /usr/local/lib/python3.7/dist-packages (from camelot-py[cv]) (3.0.10)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.7/dist-packages (from camelot-py[cv]) (0.8.9)
Requirement already satisfied: chardet>=3.0.4 in /usr/local/lib/python3.7/dist-packages (from camelot-py[cv]) (3.0.4)
Requirement already satisfied: PyPDF2>=1.26.0 in /usr/local/lib/python3.7/dist-packages (from camelot-py[cv]) (2.0.0)
Requirement already satisfied: click>=6.7 in /usr/local/lib/python3.7/dist-packages (from camelot-py[cv]) (7.1.2)
Requirement already satisfied: pdfminer.six>=20200726 in /usr/local/lib/python3.7/dist-packages (from camelot-py[cv]) (20220524)
Requirement already satisfied: ghostscript>=0.7 in /usr/local/lib/python3.7/dist-packages (from camelot-py[cv]) (0.7)
Requirement already satisfied: opencv-python>=3.4.2.17 in /usr/local/lib/python3.7/dist-packages (from camelot-py[cv]) (4.1.2.30)
Requirement already satisfied: pdftopng>=0.2.3 in /usr/local/lib/python3.7/dist-packages (from camelot-py[cv]) (0.2.3)
Requirement already satisfied: setuptools>=38.6.0 in /usr/local/lib/python3.7/dist-packages (from ghostscript>=0.7->camelot-py[cv]) (57.4.0)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.7/dist-packages (from openpyxl>=2.5.8->camelot-py[cv]) (1.1.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from pdfminer.six>=20200726->camelot-py[cv]) (2.0.12)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.7/dist-packages (from pdfminer.six>=20200726->camelot-py[cv]) (37.0.2)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.7/dist-packages (from cryptography>=36.0.0->pdfminer.six>=20200726->camelot-py[cv]) (1.15.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six>=20200726->camelot-py[cv]) (2.21)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from PyPDF2>=1.26.0->camelot-py[cv]) (4.2.0)

In [13]:
!sudo apt install ghostscript

Reading package lists... Done
Building dependency tree
Reading state information... Done
ghostscript is already the newest version (9.26~dfsg+0-0ubuntu0.18.04.16).
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 42 not upgraded.

In [ ]:
#pip3 install camelot-py[cv] tabula-py for linux or windows command is pip3 install camelot-py[cv] tabula-py

In [17]:
import camelot
 
# extract all the tables in the PDF file
abc = camelot.read_pdf("1.pdf")   #address of file location
 
# print the first table as Pandas DataFrame

In [18]:
abc

In [19]:
print(abc[0].df)

             0            1
0    INVOICE #         DATE
1         5536   2018/08/17
2  CUSTOMER ID        TERMS
3           97  Net 30 Days

In [20]:
import camelot

# PDF file to extract tables from
file = "1.pdf"

In [21]:
# extract all the tables in the PDF file
tables = camelot.read_pdf(file)

In [22]:
# number of tables extracted
print("Total tables extracted:", tables.n)

Total tables extracted: 2

In [24]:
# print the first table as Pandas DataFrame
print(tables[1].df)

                                  0                                  1  \
0                       DESCRIPTION                        QTY (hours)
1  Service Fee\nAdditional Services                               2\n7
2      Thank you for your business!  TOTAL\n                  \n925,00

                                2  \
0                  UNIT PRICE ($)
1  200,00\n               \n75,00
2

                                                   3
0                                         AMOUNT ($)
1  400,00\n                        \n525,00\n    ...
2

In [ ]:
# export individually as CSV
tables[0].to_csv("foo.csv")

In [ ]:
# export individually as Excel (.xlsx extension)
tables[0].to_excel("foo.xlsx")

In [28]:
# or export all in a zip
#tables.export("foo.csv", f="csv", compress=True)

In [27]:
tables[0].parsing_report

{'accuracy': 100.0, 'order': 1, 'page': 1, 'whitespace': 0.0}

In [26]:
# export to HTML
tables.export("foo.html", f="html")

In [34]:
!pip install beautifulsoup4

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (4.6.3)

In [35]:
!pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.21.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [49]:
# Importing the required modules
import os
import sys
import pandas as pd
from bs4 import BeautifulSoup

path = 'foo-page-1-table-2.html'

# empty list
data = []

# for getting the header from
# the HTML file
list_header = []
soup = BeautifulSoup(open(path),'html.parser')
header = soup.find_all("table")[0].find("tr")

for items in header:
	try:
		list_header.append(items.get_text())
	except:
		continue

# for getting the data
HTML_data = soup.find_all("table")[0].find_all("tr")[1:]

for element in HTML_data:
	sub_data = []
	for sub_element in element:
		try:
			sub_data.append(sub_element.get_text()).strip('\n')
		except:
			continue
	data.append(sub_data)

# Storing the data into Pandas
# DataFrame
dataFrame = pd.DataFrame(data = data, columns = list_header)

# Converting Pandas DataFrame
# into CSV file
dataFrame.to_csv('k4.csv')

In [54]:
# Importing the required modules
import os
import sys
import pandas as pd
from bs4 import BeautifulSoup

path = 'foo-page-1-table-2.html'

# empty list
data = []

# for getting the header from
# the HTML file
list_header = []
soup = BeautifulSoup(open(path),'html.parser')
header = soup.find_all("table")[0].find("tr")

for items in header:
	try:
		list_header.append(items.get_text())
	except:
		continue

# for getting the data
HTML_data = soup.find_all("table")[0].find_all("tr")[1:]

for element in HTML_data:
	sub_data = []
	for sub_element in element:
		try:
			sub_data.append((sub_element.get_text()).replace("\n", ""))#.strip()
		except:
			continue
	data.append(sub_data)

# Storing the data into Pandas
# DataFrame
dataFrame = pd.DataFrame(data = data, columns = list_header)

# Converting Pandas DataFrame
# into CSV file
dataFrame.to_csv('k56.csv')

In [55]:
import camelot as cam
table = cam.read_pdf("1.pdf", pages = 'all', flavor = 'stream')

In [56]:
print(table[0])
table[0].df
#table[0].to_excel("3.xlsx", index=False)

<Table shape=(36, 4)>

,0,1,2,3
0,,,,INVOICE
1,1 Main Road,,,
2,Johannesburg,,,
3,South Africa,INVOICE #,,DATE
4,leon@robopro.co,5536,,2018/08/17
5,,CUSTOMER ID,,TERMS
6,,97,,Net 30 Days
7,BILL TO,,,
8,Denny Barkaway,,,
9,Jamia,,,
10,8 Prentice Road,,,
11,Xihanling,,,
12,354-626-9437,,,
13,dbarkawayl7@state.tx.us,,,
14,DESCRIPTION,QTY (hours),UNIT PRICE ($),AMOUNT ($)
15,Service Fee,2,"200,00","400,00"
16,Additional Services,7,"75,00","525,00"
17,,,,-
18,,,,-
19,,,,-
20,,,,-
21,,,,-
22,,,,-
23,,,,-
24,,,,-
25,,,,-
26,,,,-
27,,,,-
28,,,,-
29,,,,-
30,,,,-
31,,,,-
32,,,,-
33,Thank you for your business!,TOTAL,,"925,00"
34,,"If you have any questions about this invoice, ...",,
35,,"[Leon, leon@robopro.co]",,

In [57]:
# export to HTML
tables.export("1.html", f="html")

In [59]:
# Importing the required modules
import os
import sys
import pandas as pd
from bs4 import BeautifulSoup

path = '1-page-1-table-2.html'

# empty list
data = []

# for getting the header from
# the HTML file
list_header = []
soup = BeautifulSoup(open(path),'html.parser')
header = soup.find_all("table")[0].find("tr")

for items in header:
	try:
		list_header.append(items.get_text())
	except:
		continue

# for getting the data
HTML_data = soup.find_all("table")[0].find_all("tr")[1:]

for element in HTML_data:
	sub_data = []
	for sub_element in element:
		try:
			sub_data.append(sub_element.get_text())#.strip('\n')
		except:
			continue
	data.append(sub_data)

# Storing the data into Pandas
# DataFrame
dataFrame = pd.DataFrame(data = data, columns = list_header)

# Converting Pandas DataFrame
# into CSV file
dataFrame.to_csv('k4.csv')

In [60]:
dataFrame

,,0,1,2,3
0,0,DESCRIPTION,QTY (hours),UNIT PRICE ($),AMOUNT ($)
1,1,Service Fee\nAdditional Services,2\n7,"200,00\n \n75,00","400,00\n \n525,00\n ..."
2,2,Thank you for your business!,"TOTAL\n \n925,00",,

In [61]:
# Importing the required modules
import os
import sys
import pandas as pd
from bs4 import BeautifulSoup

path = '1-page-1-table-1.html'

# empty list
data = []

# for getting the header from
# the HTML file
list_header = []
soup = BeautifulSoup(open(path),'html.parser')
header = soup.find_all("table")[0].find("tr")

for items in header:
	try:
		list_header.append(items.get_text())
	except:
		continue

# for getting the data
HTML_data = soup.find_all("table")[0].find_all("tr")[1:]

for element in HTML_data:
	sub_data = []
	for sub_element in element:
		try:
			sub_data.append(sub_element.get_text())#.strip('\n')
		except:
			continue
	data.append(sub_data)

# Storing the data into Pandas
# DataFrame
dataFrame = pd.DataFrame(data = data, columns = list_header)

# Converting Pandas DataFrame
# into CSV file
#dataFrame.to_csv('k4.csv')
dataFrame

                0            1
0  0    INVOICE #         DATE
1  1         5536   2018/08/17
2  2  CUSTOMER ID        TERMS
3  3           97  Net 30 Days

In [ ]:
import tabula
import os

In [ ]:
# read PDF file
tables = tabula.read_pdf("test1.pdf", pages="all")

In [ ]:
# save them in a folder
folder_name = "tables"
if not os.path.isdir(folder_name):
    os.mkdir(folder_name)
# iterate over extracted tables and export as excel individually
for i, table in enumerate(tables, start=1):
    table.to_excel(os.path.join(folder_name, f"table_{i}.xlsx"), index=False)

In [ ]:
# convert all tables of a PDF file into a single CSV file
# supported output_formats are "csv", "json" or "tsv"
tabula.convert_into("test1.pdf", "output.csv", output_format="csv", pages="all")

In [ ]:
# convert all PDFs in a folder into CSV format
# `pdfs` folder should exist in the current directory
tabula.convert_into_by_batch("tables", output_format="csv", pages="all")

In [ ]:
!pip install excalibur-py[dev]

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting excalibur-py[dev]
  Downloading excalibur_py-0.4.3-py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 5.0 MB/s
Requirement already satisfied: SQLAlchemy>=1.2.12 in /usr/local/lib/python3.7/dist-packages (from excalibur-py[dev]) (1.4.36)
Collecting celery>=4.1.1
  Downloading celery-5.2.7-py3-none-any.whl (405 kB)
     |████████████████████████████████| 405 kB 55.5 MB/s
Collecting Werkzeug<1.0.0
  Downloading Werkzeug-0.16.1-py2.py3-none-any.whl (327 kB)
     |████████████████████████████████| 327 kB 55.8 MB/s
Requirement already satisfied: camelot-py[cv]>=0.7.1 in /usr/local/lib/python3.7/dist-packages (from excalibur-py[dev]) (0.10.1)
Requirement already satisfied: Flask>=1.0.2 in /usr/local/lib/python3.7/dist-packages (from excalibur-py[dev]) (1.1.4)
Requirement already satisfied: Click>=7.0 in /usr/local/lib/python3.7/dist-packages (from excalibur-py[dev]) (7.1.2)
Collecting configparser<3.6.0,>=3.5.0
  Downloading configparser-3.5.3-py3-none-any.whl (21 kB)
Collecting pytest-runner>=4.2
  Downloading pytest_runner-6.0.0-py3-none-any.whl (7.2 kB)
Collecting pytest>=3.8.0
  Downloading pytest-7.1.2-py3-none-any.whl (297 kB)
     |████████████████████████████████| 297 kB 40.6 MB/s
Collecting pytest-cov>=2.6.0
  Downloading pytest_cov-3.0.0-py3-none-any.whl (20 kB)
Collecting codecov>=2.0.15
  Downloading codecov-2.1.12-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: Sphinx>=1.8.1 in /usr/local/lib/python3.7/dist-packages (from excalibur-py[dev]) (1.8.6)
Requirement already satisfied: chardet>=3.0.4 in /usr/local/lib/python3.7/dist-packages (from camelot-py[cv]>=0.7.1->excalibur-py[dev]) (3.0.4)
Requirement already satisfied: pdfminer.six>=20200726 in /usr/local/lib/python3.7/dist-packages (from camelot-py[cv]>=0.7.1->excalibur-py[dev]) (20220524)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.7/dist-packages (from camelot-py[cv]>=0.7.1->excalibur-py[dev]) (1.21.6)
Requirement already satisfied: pandas>=0.23.4 in /usr/local/lib/python3.7/dist-packages (from camelot-py[cv]>=0.7.1->excalibur-py[dev]) (1.3.5)
Requirement already satisfied: PyPDF2>=1.26.0 in /usr/local/lib/python3.7/dist-packages (from camelot-py[cv]>=0.7.1->excalibur-py[dev]) (2.0.0)
Requirement already satisfied: openpyxl>=2.5.8 in /usr/local/lib/python3.7/dist-packages (from camelot-py[cv]>=0.7.1->excalibur-py[dev]) (3.0.10)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.7/dist-packages (from camelot-py[cv]>=0.7.1->excalibur-py[dev]) (0.8.9)
Requirement already satisfied: ghostscript>=0.7 in /usr/local/lib/python3.7/dist-packages (from camelot-py[cv]>=0.7.1->excalibur-py[dev]) (0.7)
Requirement already satisfied: pdftopng>=0.2.3 in /usr/local/lib/python3.7/dist-packages (from camelot-py[cv]>=0.7.1->excalibur-py[dev]) (0.2.3)
Requirement already satisfied: opencv-python>=3.4.2.17 in /usr/local/lib/python3.7/dist-packages (from camelot-py[cv]>=0.7.1->excalibur-py[dev]) (4.1.2.30)
Collecting vine<6.0,>=5.0.0
  Downloading vine-5.0.0-py2.py3-none-any.whl (9.4 kB)
Collecting billiard<4.0,>=3.6.4.0
  Downloading billiard-3.6.4.0-py3-none-any.whl (89 kB)
     |████████████████████████████████| 89 kB 7.1 MB/s
Collecting click-didyoumean>=0.0.3
  Downloading click_didyoumean-0.3.0-py3-none-any.whl (2.7 kB)
Collecting kombu<6.0,>=5.2.3
  Downloading kombu-5.2.4-py3-none-any.whl (189 kB)
     |████████████████████████████████| 189 kB 45.2 MB/s
Requirement already satisfied: importlib-metadata>=1.4.0 in /usr/local/lib/python3.7/dist-packages (from celery>=4.1.1->excalibur-py[dev]) (4.11.3)
Collecting Click>=7.0
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 4.9 MB/s
Requirement already satisfied: pytz>=2021.3 in /usr/local/lib/python3.7/dist-packages (from celery>=4.1.1->excalibur-py[dev]) (2022.1)
Collecting click-repl>=0.2.0
  Downloading click_repl-0.2.0-py3-none-any.whl (5.2 kB)
Collecting click-plugins>=1.1.1
  Downloading click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from click-repl>=0.2.0->celery>=4.1.1->excalibur-py[dev]) (1.15.0)
Requirement already satisfied: prompt-toolkit in /usr/local/lib/python3.7/dist-packages (from click-repl>=0.2.0->celery>=4.1.1->excalibur-py[dev]) (1.0.18)
Requirement already satisfied: coverage in /usr/local/lib/python3.7/dist-packages (from codecov>=2.0.15->excalibur-py[dev]) (3.7.1)
Requirement already satisfied: requests>=2.7.9 in /usr/local/lib/python3.7/dist-packages (from codecov>=2.0.15->excalibur-py[dev]) (2.23.0)
Requirement already satisfied: Jinja2<3.0,>=2.10.1 in /usr/local/lib/python3.7/dist-packages (from Flask>=1.0.2->excalibur-py[dev]) (2.11.3)
Requirement already satisfied: itsdangerous<2.0,>=0.24 in /usr/local/lib/python3.7/dist-packages (from Flask>=1.0.2->excalibur-py[dev]) (1.1.0)
Collecting Flask>=1.0.2
  Downloading Flask-2.1.2-py3-none-any.whl (95 kB)
     |████████████████████████████████| 95 kB 3.1 MB/s
Collecting Jinja2>=3.0
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 56.0 MB/s
Collecting itsdangerous>=2.0
  Downloading itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting Flask>=1.0.2
  Downloading Flask-2.1.1-py3-none-any.whl (95 kB)
     |████████████████████████████████| 95 kB 3.5 MB/s
  Downloading Flask-2.1.0-py3-none-any.whl (95 kB)
     |████████████████████████████████| 95 kB 3.6 MB/s
  Downloading Flask-2.0.3-py3-none-any.whl (95 kB)
     |████████████████████████████████| 95 kB 4.1 MB/s
  Downloading Flask-2.0.2-py3-none-any.whl (95 kB)
     |████████████████████████████████| 95 kB 3.1 MB/s
  Downloading Flask-2.0.1-py3-none-any.whl (94 kB)
     |████████████████████████████████| 94 kB 3.2 MB/s
  Downloading Flask-2.0.0-py3-none-any.whl (93 kB)
     |████████████████████████████████| 93 kB 1.3 MB/s
  Downloading Flask-1.1.3-py2.py3-none-any.whl (94 kB)
     |████████████████████████████████| 94 kB 2.6 MB/s
  Downloading Flask-1.1.2-py2.py3-none-any.whl (94 kB)
     |████████████████████████████████| 94 kB 2.5 MB/s
Requirement already satisfied: setuptools>=38.6.0 in /usr/local/lib/python3.7/dist-packages (from ghostscript>=0.7->camelot-py[cv]>=0.7.1->excalibur-py[dev]) (57.4.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=1.4.0->celery>=4.1.1->excalibur-py[dev]) (3.8.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=1.4.0->celery>=4.1.1->excalibur-py[dev]) (4.2.0)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from Jinja2<3.0,>=2.10.1->Flask>=1.0.2->excalibur-py[dev]) (2.0.1)
Collecting amqp<6.0.0,>=5.0.9
  Downloading amqp-5.1.1-py3-none-any.whl (50 kB)
     |████████████████████████████████| 50 kB 5.9 MB/s
Requirement already satisfied: cached-property in /usr/local/lib/python3.7/dist-packages (from kombu<6.0,>=5.2.3->celery>=4.1.1->excalibur-py[dev]) (1.5.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.7/dist-packages (from openpyxl>=2.5.8->camelot-py[cv]>=0.7.1->excalibur-py[dev]) (1.1.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23.4->camelot-py[cv]>=0.7.1->excalibur-py[dev]) (2.8.2)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.7/dist-packages (from pdfminer.six>=20200726->camelot-py[cv]>=0.7.1->excalibur-py[dev]) (37.0.2)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from pdfminer.six>=20200726->camelot-py[cv]>=0.7.1->excalibur-py[dev]) (2.0.12)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.7/dist-packages (from cryptography>=36.0.0->pdfminer.six>=20200726->camelot-py[cv]>=0.7.1->excalibur-py[dev]) (1.15.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six>=20200726->camelot-py[cv]>=0.7.1->excalibur-py[dev]) (2.21)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.7/dist-packages (from pytest>=3.8.0->excalibur-py[dev]) (21.4.0)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.7/dist-packages (from pytest>=3.8.0->excalibur-py[dev]) (1.1.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from pytest>=3.8.0->excalibur-py[dev]) (21.3)
Requirement already satisfied: tomli>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from pytest>=3.8.0->excalibur-py[dev]) (2.0.1)
Requirement already satisfied: py>=1.8.2 in /usr/local/lib/python3.7/dist-packages (from pytest>=3.8.0->excalibur-py[dev]) (1.11.0)
Collecting pluggy<2.0,>=0.12
  Downloading pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting coverage[toml]>=5.2.1
  Downloading coverage-6.4-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (208 kB)
     |████████████████████████████████| 208 kB 57.6 MB/s
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.7.9->codecov>=2.0.15->excalibur-py[dev]) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.7.9->codecov>=2.0.15->excalibur-py[dev]) (2022.5.18.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.7.9->codecov>=2.0.15->excalibur-py[dev]) (2.10)
Requirement already satisfied: babel!=2.0,>=1.3 in /usr/local/lib/python3.7/dist-packages (from Sphinx>=1.8.1->excalibur-py[dev]) (2.10.1)
Requirement already satisfied: Pygments>=2.0 in /usr/local/lib/python3.7/dist-packages (from Sphinx>=1.8.1->excalibur-py[dev]) (2.6.1)
Requirement already satisfied: imagesize in /usr/local/lib/python3.7/dist-packages (from Sphinx>=1.8.1->excalibur-py[dev]) (1.3.0)
Requirement already satisfied: snowballstemmer>=1.1 in /usr/local/lib/python3.7/dist-packages (from Sphinx>=1.8.1->excalibur-py[dev]) (2.2.0)
Requirement already satisfied: docutils<0.18,>=0.11 in /usr/local/lib/python3.7/dist-packages (from Sphinx>=1.8.1->excalibur-py[dev]) (0.17.1)
Requirement already satisfied: alabaster<0.8,>=0.7 in /usr/local/lib/python3.7/dist-packages (from Sphinx>=1.8.1->excalibur-py[dev]) (0.7.12)
Requirement already satisfied: sphinxcontrib-websupport in /usr/local/lib/python3.7/dist-packages (from Sphinx>=1.8.1->excalibur-py[dev]) (1.2.4)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.7/dist-packages (from SQLAlchemy>=1.2.12->excalibur-py[dev]) (1.1.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->pytest>=3.8.0->excalibur-py[dev]) (3.0.9)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit->click-repl>=0.2.0->celery>=4.1.1->excalibur-py[dev]) (0.2.5)
Requirement already satisfied: sphinxcontrib-serializinghtml in /usr/local/lib/python3.7/dist-packages (from sphinxcontrib-websupport->Sphinx>=1.8.1->excalibur-py[dev]) (1.1.5)
Installing collected packages: vine, Click, amqp, Werkzeug, pluggy, kombu, coverage, click-repl, click-plugins, click-didyoumean, billiard, pytest, Flask, configparser, celery, pytest-runner, pytest-cov, excalibur-py, codecov
  Attempting uninstall: Click
    Found existing installation: click 7.1.2
    Uninstalling click-7.1.2:
      Successfully uninstalled click-7.1.2
  Attempting uninstall: Werkzeug
    Found existing installation: Werkzeug 1.0.1
    Uninstalling Werkzeug-1.0.1:
      Successfully uninstalled Werkzeug-1.0.1
  Attempting uninstall: pluggy
    Found existing installation: pluggy 0.7.1
    Uninstalling pluggy-0.7.1:
      Successfully uninstalled pluggy-0.7.1
  Attempting uninstall: coverage
    Found existing installation: coverage 3.7.1
    Uninstalling coverage-3.7.1:
      Successfully uninstalled coverage-3.7.1
  Attempting uninstall: pytest
    Found existing installation: pytest 3.6.4
    Uninstalling pytest-3.6.4:
      Successfully uninstalled pytest-3.6.4
  Attempting uninstall: Flask
    Found existing installation: Flask 1.1.4
    Uninstalling Flask-1.1.4:
      Successfully uninstalled Flask-1.1.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datascience 0.10.6 requires coverage==3.7.1, but you have coverage 6.4 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
coveralls 0.5 requires coverage<3.999,>=3.6, but you have coverage 6.4 which is incompatible.
Successfully installed Click-8.1.3 Flask-1.1.2 Werkzeug-0.16.1 amqp-5.1.1 billiard-3.6.4.0 celery-5.2.7 click-didyoumean-0.3.0 click-plugins-1.1.1 click-repl-0.2.0 codecov-2.1.12 configparser-3.5.3 coverage-6.4 excalibur-py-0.4.3 kombu-5.2.4 pluggy-1.0.0 pytest-7.1.2 pytest-cov-3.0.0 pytest-runner-6.0.0 vine-5.0.0