<a href="https://colab.research.google.com/github/rabiyulfahimhasim786/opencv-basics/blob/main/pdf_tables_toexcel%26csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install camelot-py[cv] tabula-py

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting camelot-py[cv]
  Downloading camelot_py-0.10.1-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 14 kB/s
Collecting tabula-py
  Downloading tabula_py-2.4.0-py3-none-any.whl (12.0 MB)
     |████████████████████████████████| 12.0 MB 12.8 MB/s
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.7/dist-packages (from tabula-py) (1.3.5)
Collecting distro
  Downloading distro-1.7.0-py3-none-any.whl (20 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from tabula-py) (1.21.6)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.3->tabula-py) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.3->tabula-py) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.25.3->tabula-py) (1.15.0)
Requirement already satisfied: openpyxl>=2.5.8 in /usr/local/lib/python3.7/dist-packages (from camelot-py[cv]) (3.0.10)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.7/dist-packages (from camelot-py[cv]) (0.8.9)
Collecting pdfminer.six>=20200726
  Downloading pdfminer.six-20220524-py3-none-any.whl (5.6 MB)
     |████████████████████████████████| 5.6 MB 46.1 MB/s
Collecting PyPDF2>=1.26.0
  Downloading PyPDF2-2.0.0-py3-none-any.whl (88 kB)
     |████████████████████████████████| 88 kB 8.8 MB/s
Requirement already satisfied: click>=6.7 in /usr/local/lib/python3.7/dist-packages (from camelot-py[cv]) (7.1.2)
Requirement already satisfied: chardet>=3.0.4 in /usr/local/lib/python3.7/dist-packages (from camelot-py[cv]) (3.0.4)
Requirement already satisfied: opencv-python>=3.4.2.17 in /usr/local/lib/python3.7/dist-packages (from camelot-py[cv]) (4.1.2.30)
Collecting pdftopng>=0.2.3
  Downloading pdftopng-0.2.3-cp37-cp37m-manylinux2010_x86_64.whl (11.7 MB)
     |████████████████████████████████| 11.7 MB 25.1 MB/s
Collecting ghostscript>=0.7
  Downloading ghostscript-0.7-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: setuptools>=38.6.0 in /usr/local/lib/python3.7/dist-packages (from ghostscript>=0.7->camelot-py[cv]) (57.4.0)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.7/dist-packages (from openpyxl>=2.5.8->camelot-py[cv]) (1.1.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from pdfminer.six>=20200726->camelot-py[cv]) (2.0.12)
Collecting cryptography>=36.0.0
  Downloading cryptography-37.0.2-cp36-abi3-manylinux_2_24_x86_64.whl (4.0 MB)
     |████████████████████████████████| 4.0 MB 28.3 MB/s
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.7/dist-packages (from cryptography>=36.0.0->pdfminer.six>=20200726->camelot-py[cv]) (1.15.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six>=20200726->camelot-py[cv]) (2.21)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from PyPDF2>=1.26.0->camelot-py[cv]) (4.2.0)
Installing collected packages: cryptography, PyPDF2, pdfminer.six, pdftopng, ghostscript, distro, camelot-py, tabula-py
Successfully installed PyPDF2-2.0.0 camelot-py-0.10.1 cryptography-37.0.2 distro-1.7.0 ghostscript-0.7 pdfminer.six-20220524 pdftopng-0.2.3 tabula-py-2.4.0

In [2]:
!sudo apt install ghostscript

Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  fonts-droid-fallback fonts-noto-mono gsfonts libcupsfilters1 libcupsimage2
  libgs9 libgs9-common libijs-0.35 libjbig2dec0 poppler-data
Suggested packages:
  fonts-noto ghostscript-x poppler-utils fonts-japanese-mincho
  | fonts-ipafont-mincho fonts-japanese-gothic | fonts-ipafont-gothic
  fonts-arphic-ukai fonts-arphic-uming fonts-nanum
The following NEW packages will be installed:
  fonts-droid-fallback fonts-noto-mono ghostscript gsfonts libcupsfilters1
  libcupsimage2 libgs9 libgs9-common libijs-0.35 libjbig2dec0 poppler-data
0 upgraded, 11 newly installed, 0 to remove and 42 not upgraded.
Need to get 14.1 MB of archives.
After this operation, 49.9 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 fonts-droid-fallback all 1:6.0.1r16-1.1 [1,805 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic/main amd64 poppler-data all 0.4.8-2 [1,479 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic/main amd64 fonts-noto-mono all 20171026-2 [75.5 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libcupsimage2 amd64 2.2.7-1ubuntu2.8 [18.6 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/main amd64 libijs-0.35 amd64 0.35-13 [15.5 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic/main amd64 libjbig2dec0 amd64 0.13-6 [55.9 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libgs9-common all 9.26~dfsg+0-0ubuntu0.18.04.16 [5,093 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libgs9 amd64 9.26~dfsg+0-0ubuntu0.18.04.16 [2,265 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 ghostscript amd64 9.26~dfsg+0-0ubuntu0.18.04.16 [51.3 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/main amd64 gsfonts all 1:8.11+urwcyr1.0.7~pre44-4.4 [3,120 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libcupsfilters1 amd64 1.20.2-0ubuntu3.1 [108 kB]
Fetched 14.1 MB in 2s (6,924 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 11.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package fonts-droid-fallback.
(Reading database ... 155629 files and directories currently installed.)
Preparing to unpack .../00-fonts-droid-fallback_1%3a6.0.1r16-1.1_all.deb ...
Unpacking fonts-droid-fallback (1:6.0.1r16-1.1) ...
Selecting previously unselected package poppler-data.
Preparing to unpack .../01-poppler-data_0.4.8-2_all.deb ...
Unpacking poppler-data (0.4.8-2) ...
Selecting previously unselected package fonts-noto-mono.
Preparing to unpack .../02-fonts-noto-mono_20171026-2_all.deb ...
Unpacking fonts-noto-mono (20171026-2) ...
Selecting previously unselected package libcupsimage2:amd64.
Preparing to unpack .../03-libcupsimage2_2.2.7-1ubuntu2.8_amd64.deb ...
Unpacking libcupsimage2:amd64 (2.2.7-1ubuntu2.8) ...
Selecting previously unselected package libijs-0.35:amd64.
Preparing to unpack .../04-libijs-0.35_0.35-13_amd64.deb ...
Unpacking libijs-0.35:amd64 (0.35-13) ...
Selecting previously unselected package libjbig2dec0:amd64.
Preparing to unpack .../05-libjbig2dec0_0.13-6_amd64.deb ...
Unpacking libjbig2dec0:amd64 (0.13-6) ...
Selecting previously unselected package libgs9-common.
Preparing to unpack .../06-libgs9-common_9.26~dfsg+0-0ubuntu0.18.04.16_all.deb ...
Unpacking libgs9-common (9.26~dfsg+0-0ubuntu0.18.04.16) ...
Selecting previously unselected package libgs9:amd64.
Preparing to unpack .../07-libgs9_9.26~dfsg+0-0ubuntu0.18.04.16_amd64.deb ...
Unpacking libgs9:amd64 (9.26~dfsg+0-0ubuntu0.18.04.16) ...
Selecting previously unselected package ghostscript.
Preparing to unpack .../08-ghostscript_9.26~dfsg+0-0ubuntu0.18.04.16_amd64.deb ...
Unpacking ghostscript (9.26~dfsg+0-0ubuntu0.18.04.16) ...
Selecting previously unselected package gsfonts.
Preparing to unpack .../09-gsfonts_1%3a8.11+urwcyr1.0.7~pre44-4.4_all.deb ...
Unpacking gsfonts (1:8.11+urwcyr1.0.7~pre44-4.4) ...
Selecting previously unselected package libcupsfilters1:amd64.
Preparing to unpack .../10-libcupsfilters1_1.20.2-0ubuntu3.1_amd64.deb ...
Unpacking libcupsfilters1:amd64 (1.20.2-0ubuntu3.1) ...
Setting up libgs9-common (9.26~dfsg+0-0ubuntu0.18.04.16) ...
Setting up fonts-droid-fallback (1:6.0.1r16-1.1) ...
Setting up gsfonts (1:8.11+urwcyr1.0.7~pre44-4.4) ...
Setting up poppler-data (0.4.8-2) ...
Setting up fonts-noto-mono (20171026-2) ...
Setting up libcupsfilters1:amd64 (1.20.2-0ubuntu3.1) ...
Setting up libcupsimage2:amd64 (2.2.7-1ubuntu2.8) ...
Setting up libjbig2dec0:amd64 (0.13-6) ...
Setting up libijs-0.35:amd64 (0.35-13) ...
Setting up libgs9:amd64 (9.26~dfsg+0-0ubuntu0.18.04.16) ...
Setting up ghostscript (9.26~dfsg+0-0ubuntu0.18.04.16) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for fontconfig (2.12.6-0ubuntu2) ...
Processing triggers for libc-bin (2.27-3ubuntu1.3) ...
/sbin/ldconfig.real: /usr/local/lib/python3.7/dist-packages/ideep4py/lib/libmkldnn.so.0 is not a symbolic link

In [3]:
import camelot
 
# extract all the tables in the PDF file
abc = camelot.read_pdf("1.pdf")   #address of file location
 
# print the first table as Pandas DataFrame

/usr/local/lib/python3.7/dist-packages/camelot/parsers/lattice.py:413: UserWarning: page-1 is image-based, camelot only works on text-based pages.
  " text-based pages.".format(os.path.basename(self.rootname))

In [4]:
abc

In [12]:
import camelot as cam
table = cam.read_pdf("2.pdf", pages = 'all', flavor = 'stream')

In [13]:
table

In [20]:
print(table[0])
table[0].df
#table[0].to_excel("3.xlsx", index=False)

<Table shape=(22, 3)>

,0,1,2
0,,,647-444-1234 \noR Nga)
1,| IN VO | C =,,CMe liay \nfo \nReel) \nSrTiO
2,,,Pe a oR) \nZIP CODE
3,Billed To,Invoice Number,Invoice Total
4,,000000,
5,\ Clow aes,,$4520.00
6,"City, State, Country",Date,
7,ZIP CODE,10/07/14,
8,Description,,Unit Cost \nQty / Hr Rate \nAmount
9,‘Your item Name,,$1000 \n1 \n1000
10,Item description goes here,,
11,‘Your item Name,,$1000 \n1 \n1000
12,Item description goes here,,
13,‘Your item Name,,$1000 \n1 \n1000
14,Item description goes here,,
15,Your item Name,,$1000 \n1 \n1000
16,Item description goes here,,
17,,,Subtotal \n$4000.00
18,,,Tax \n$520.00
19,,,Total \n$4520.00
20,Invoice Terms,,
21,Ex. Please pay your invoice by....,,$4520.00\nAmount Due (USD)

In [21]:
# export to HTML
table.export("1.html", f="html")

In [22]:
# Importing the required modules
import os
import sys
import pandas as pd
from bs4 import BeautifulSoup

path = '1-page-1-table-1.html'

# empty list
data = []

# for getting the header from
# the HTML file
list_header = []
soup = BeautifulSoup(open(path),'html.parser')
header = soup.find_all("table")[0].find("tr")

for items in header:
	try:
		list_header.append(items.get_text())
	except:
		continue

# for getting the data
HTML_data = soup.find_all("table")[0].find_all("tr")[1:]

for element in HTML_data:
	sub_data = []
	for sub_element in element:
		try:
			sub_data.append(sub_element.get_text())#.strip('\n')
		except:
			continue
	data.append(sub_data)

# Storing the data into Pandas
# DataFrame
dataFrame = pd.DataFrame(data = data, columns = list_header)

# Converting Pandas DataFrame
# into CSV file
dataFrame.to_csv('k4.csv')

In [23]:
dataFrame

,,0,1,2
0,0,,,647-444-1234 \noR Nga)
1,1,| IN VO | C =,,CMe liay \nfo \nReel) \nSrTiO
2,2,,,Pe a oR) \nZIP CODE
3,3,Billed To,Invoice Number,Invoice Total
4,4,,000000,
5,5,\ Clow aes,,$4520.00
6,6,"City, State, Country",Date,
7,7,ZIP CODE,10/07/14,
8,8,Description,,Unit Cost \nQty / Hr Rate \nAmount
9,9,‘Your item Name,,$1000 \n1 \n1000
10,10,Item description goes here,,
11,11,‘Your item Name,,$1000 \n1 \n1000
12,12,Item description goes here,,
13,13,‘Your item Name,,$1000 \n1 \n1000
14,14,Item description goes here,,
15,15,Your item Name,,$1000 \n1 \n1000
16,16,Item description goes here,,
17,17,,,Subtotal \n$4000.00
18,18,,,Tax \n$520.00
19,19,,,Total \n$4520.00
20,20,Invoice Terms,,
21,21,Ex. Please pay your invoice by....,,$4520.00\nAmount Due (USD)

In [24]:
# Importing pandas
import pandas as pd
  
# The webpage URL whose table we want to extract
#url = "https://www.geeksforgeeks.org/extended-operators-in-relational-algebra/"
url = '1-page-1-table-1.html'
# Assign the table data to a Pandas dataframe
table = pd.read_html(url)[0]
  
# Store the dataframe in Excel file
table.to_excel("data.xlsx")

In [25]:
table

,Unnamed: 0,0,1,2
0,0,NaN,NaN,647-444-1234 \noR Nga)
1,1,| IN VO | C =,NaN,CMe liay \nfo \nReel) \nSrTiO
2,2,NaN,NaN,Pe a oR) \nZIP CODE
3,3,Billed To,Invoice Number,Invoice Total
4,4,NaN,000000,NaN
5,5,\ Clow aes,NaN,$4520.00
6,6,"City, State, Country",Date,NaN
7,7,ZIP CODE,10/07/14,NaN
8,8,Description,NaN,Unit Cost \nQty / Hr Rate \nAmount
9,9,âYour item Name,NaN,$1000 \n1 \n1000
10,10,Item description goes here,NaN,NaN
11,11,âYour item Name,NaN,$1000 \n1 \n1000
12,12,Item description goes here,NaN,NaN
13,13,âYour item Name,NaN,$1000 \n1 \n1000
14,14,Item description goes here,NaN,NaN
15,15,Your item Name,NaN,$1000 \n1 \n1000
16,16,Item description goes here,NaN,NaN
17,17,NaN,NaN,Subtotal \n$4000.00
18,18,NaN,NaN,Tax \n$520.00
19,19,NaN,NaN,Total \n$4520.00
20,20,Invoice Terms,NaN,NaN
21,21,Ex. Please pay your invoice by....,NaN,$4520.00\nAmount Due (USD)